# @format

name: calliverse
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^14.2.7
  pinput: ^5.0.0
  intl_phone_field: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Mulish
      fonts:
        - asset: fonts/Mulish-Bold.ttf
        - asset: fonts/Mulish-Regular.ttf
          style: italic

    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-Regular.ttf
          style: italic
